function [MSB, CSB, KSB,  MSBG, CN, KN, I] = MCKSB(MSS, CSS, KSS, BM, CDAB, CKAB, NST, NDOF)

MSB = MSS;
MSB(NDOF, NDOF) = BM;
MSBG = MSB;
MSB(1:NST,NDOF) = diag(MSS);

CSB = CSS;
CN = CSS(NST,NST) + CSS(NST,NST-1);
CSB(NDOF, NDOF) = CDAB; %CN + CDAB;
CSB(NDOF,NST) = -CN;

KSB = KSS;
KN = KSS(NST,NST) + KSS(NST,NST-1);
KSB(NDOF, NDOF) = CKAB; %KN + CKAB;
KSB(NDOF,NST) = -KN;

I = ones(NDOF,1);
end

